master.py, validation_code/ConditionalLuminosityFunction.py, validation_configs/CLF_r.yaml, www/fix_permission.sh
* adding a CLF test (based on [this example](https://github.com/LSSTDESC/gcr-catalogs/blob/master/examples/CLF%20Test.ipynb)) for #9 
* test config files are now included in web output
=> add CLF test

descqa/NumberDensityVersusRedshift.py, descqa/configs/Nz_g.yaml, descqa/configs/Nz_i_Coil2004_magbin.yaml, descqa/configs/Nz_i_Coil2004_maglim.yaml, descqa/configs/Nz_i_DEEP2_JAN.yaml, descqa/configs/Nz_r_Coil2004_maglim.yaml, descqa/configs/Nz_r_DEEP2_JAN.yaml
Still need to refactor the catalog reading to be more efficient
=> Nvsz refactor complete

descqa/utils.py, tests/test_descqa_utils.py
This PR adds a new ` utils` module into `descqa`. Right now this module includes some functions needed in #38 and #51.
=> add utils module

descqa/StellarMassFunction.py
This PR updates the SMF test to use the newly creately utils module.
=> update smf test, using utils module

descqaweb/main.py, descqaweb/templates/leftpanel.html, descqaweb/templates/twopanels.html, descqaweb/twopanels.py
This PR makes it easier to share DESCQA results with URLs. Now in the two-panel view, when clicking on the files, the URL will change accordingly. The updated URL would load the same file in the right panel. 
This PR also allows display of HTML file type.
=> update URL when right panel changes

descqa/EllipticityDistribution.py
https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-02-27_1&test=ellipticity_dist_COSMOS
=> fixed norm bug

descqa/NumberDensityVersusRedshift.py, descqa/configs/Nz_i_Coil2004_maglim.yaml, descqa/configs/Nz_r_Coil2004_maglim.yaml
https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-03-05_1&test=Nz_i_Coil2004_maglim
Here is the result of running jack-knife errors on protoDC2. Fixed some other minor bugs.
=> Nz bug fix - include jack-knife errors in preparation for computing score for validation criteria

descqaweb/interface.py
Fix a bug in finding subdirectories
=> Web bug fix

descqa/configs/readiness_protoDC2.yaml
Changes nan and outlier fraction to accommodate changes in ellipticity computation (to make sizes and ellipticities consistent in all cases)
https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-03-20_4&catalog=protoDC2
=> Minor parameter update

descqa/CheckColors.py, descqa/configs/CheckColors.yaml
This is a PR corresponding to issue #74 
https://github.com/LSSTDESC/descqa/issues/74
Includes code and configuration file (CheckColors.py and CheckColors.yaml)
Outputs are user selected color-color diagrams for inspection for input catalogs:  
https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-03-02_3&test=CheckColors
=> Color check inspection test

descqa/CheckColors.py, descqa/ColorDistribution.py
This PR fixes several bugs in the color distribution test. See an example run at https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-03-26_3
It also adds tight layout to the color-color test.
=> Color dist bug fix

setup.py
This is just to update the copyright year in the setup.py
=> Update copyright year

descqarun/__init__.py, descqarun/master.py
This PR fixes an issue when the output directory does not have the right permission set.
=> Ensure output directory has the right permission

descqa/shear_test.py
Update y-axis limits of the shear test plot so that the range is more reasonable.
See https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-04-12_52&test=shear&right=2018-04/2018-04-12_52/shear/summary.png
@patricialarsen can you take a look? (I cannot assign you as a reviewer.. you need to join DESC organization! )
=> update y-axis limits of the shear test plot

descqa/clf_test.py
This PR fixes #121. Here's an example run: https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-06-26_9&test=CLF_r 
However, @evevkovacs, I wasn't able to test this on the new UM catalog. Can you point me a working GCRCatalogs that has the UM catalog in the configs? Thanks!
=> Update color cut in CLF test

descqa/CheckColors.py
=> adding mag(psf) and cModel mags to CheckColors

descqa/configs/readiness_instance.yaml
I am adding a yaml (config) file to perform readiness tests on instance catalogs.
=> Added readiness test for instance catalogs

descqa/configs/SkyArea_hires.yaml, descqa/configs/readiness_baseDC2.yaml, descqa/configs/readiness_cosmoDC2.yaml, descqa/readiness_test.py
Here are the links for these tests:
[readiness test](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-08-23_21&test=readiness_baseDC2)
The portal seems to be down so I can't link the area test, but it was in the DC2 slides for 8/24/18
=> Changes for readiness and sky area tests to run on baseDC2 and cosmoDC2

descqa/NumberDensityVersusRedshift.py
Shortened the data label and made sure that axis labels get printed on second column of plots
https://portal.nersc.gov/project/lsst/descqa/v2/?run=2019-03-15_4
=> Minor cosmetic change

run_master.sh
Updated DESC python installation is using conda environments and the original base path no longer has all the packages we need. This PR updates the python path.
=> update python path

descqa/SizeStellarMassLuminosity.py, descqa/configs/size_Mandelbaum2014_BD.yaml, descqa/configs/size_vanderWel2014_SM_Lum.yaml
Update to size test, supersedes PR #95
Revised size tests including cosmetic improvements and some corrections to the plots: [Example tests](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2019-09-16_1&catalog=cosmoDC2_v1.1.4_small)
=> Revised code for size-distribution test

descqa/EllipticityDistribution.py
Minor cosmetic updates for making figures included.
[descqa test](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2019-09-17_6&catalog=cosmoDC2_v1.1.4_small)
=> Changes to allow for making better figures

descqa/configs/color_z_red_sequence_centrals.yaml
New config file for a "redmapper" test using only centrals. Useful for comparisons with results from @erykoff  running the full RedMaPPer code.
See [this example](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2019-09-19_3&catalog=cosmoDC2_v1.1.4_small_combined_agn_allon)
=> Descqa dc2

CONTRIBUTING.md, README.md, descqarun/config.py, descqaweb/config.py, run_master_v1.sh
Fixed typo. See https://portal.nersc.gov/projecta/lsst/descqa/v2/?run=2020-01-21_8 for test run
=> Fix typo in base_url

descqa/CheckColors.py, descqa/configs/CheckColors.yaml, setup.py
https://portal.nersc.gov/cfs/lsst/descqa/v2/?run=2020-05-06_2&test=CheckColors&catalog=cosmoDC2_v1.1.4_small
=> New PR for CheckColors including updates to paths requested

index.cgi
This PR updates the CGI python executable path to use the current DESC python environment.
=> Update CGI python executable path

run_master.sh
This PR fixes #209 by loading the default modules (instead of a specific version).
=> Remove module versions

descqa/CheckColors.py
https://portal.nersc.gov/cfs/lsst/descqa/v2/?run=2020-12-08_4
or 
https://portal.nersc.gov/cfs/lsst/descqa/v2/?run=2020-12-08_2
(Truncated catalog name or not)
=> updated plots for paper - validation test CheckColors.py

descqa/shear_test.py
> If you are submitting a PR for a validation test (either adding a new one or updating an existing one), please post a link to the DESCQA web interface for the test you are submitting.
=> Loading catalog data in tomographic bins to reduce used memory.

descqa/CorrelationsTwoPoint.py
https://portal.nersc.gov/cfs/lsst/descqa/v2/?run=2020-12-09_3&test=tpcf_Zehavi2011_color
=> Changed images size for pcf_Zehavi2011_color test

run_master.sh
This PR reverts the change we made in 4c46f34 and fixes #226
=> Revert to using current python

descqaweb/bigtable.py
=> Make linter happy

.github/workflows/pythonpackage.yml
=> Update github action

README.md
Proposal for addition of specific run-one-test example in README.
> If you are submitting a PR for a validation test (either adding a new one or updating an existing one), please post a link to the DESCQA web interface for the test you are submitting.
=> Suggested addition of run_master.sh example
