LSSTDESC/descqa

- validation_code/ConditionalLuminosityFunction.py
- validation_configs/CLF_r.yaml
I've included a color cut, where the cut is determined by finding the rest frame g-r color which gives the same number density (for z<0.2) for each catalog. This isn't totally optimal, but it's the best solution until we have catalogs with the same bands.
> Added color cuts to CLF test

- descqaweb/config.py
- descqaweb/matrix.py
- descqaweb/templates/header.html
- descqaweb/templates/matrix.html
This PR moves all DESC-related web setting to config.py, so that it will be easier for other people (e.g. DESI) to use and configure the web interface.
> Move all DESC-related web setting to config.py

- v1/GCRCatalogs/__init__.py
- v1/GCRCatalogs/register.py
This is a patch to the v1 reader (adding `get_catalog_config`) so that it continue to work with the updated `descqarun`.
> Update v1 catalog register

- .travis.yml
- descqa/configs/readiness_protoDC2.yaml
- descqa/readiness_test.py
This PR updates the readiness test for protoDC2 with the following features:
- including SEDs (fixes #64)
- add more acceptable ranges (fixes #60)
- add a new feature to do simple relation checking
➡️ [Click here to see the test result from this PR](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-01-24_2&test=readiness_protoDC2&right=2018-01-24_2/readiness_protoDC2/protoDC2/SUMMARY.html) 
Can @evevkovacs @dkorytov @abensonca comment on whether the results look good? Currently the catalog is failing because some of the SED std is too big, but if that's normal we can change the acceptable ranges. 
Also, any other simple relations we should include? I only added two as a test.
> update readiness test (add SED, acceptable ranges, relation checking)

- descqa/configs/readiness_protoDC2.yaml
- descqa/readiness_test.py
This PR allows the use of `~==` in the relations to check in the readiness test. It means "all close" (by using the `np.allclose` function). Useful to comparing float-point quantities.
> use ~== for "all-close" relation in readiness test

- descqa/configs/readiness_protoDC2.yaml
Re-ran readiness test with some tweaked ranges for protoDC2 v3
https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-03-19_75&test=readiness_protoDC2&right=2018-03/2018-03-19_75/readiness_protoDC2/proto-dc2_v3.0/SUMMARY.html
> Updated ranges for protodc2_v3

- descqa/ColorDistribution.py
- descqa/configs/Color_Dist_DEEP2.yaml
- descqa/configs/Color_Dist_SDSS.yaml
- descqa/stats.py
This PR corresponds to the issue #15 
This is a first implementation of the color distribution test in DESCQA 2.
Minor changes to the CvM statistic function to allow for flexible grids and removed the success criteria.
Results of the color test on the DESCQA web interface: https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-03-04_11
> Color test

- descqa/ColorDistribution.py
This PR fixes a bug in the color distribution test that allowed the much shallower CFHTLS Wide field photometry to be included for calculating the color distribution. It now requires that only the CFHTLS Deep field photometry be used.
> Remove CFHTLS-wide objects from color distribution

- descqa/configs/readiness_protoDC2.yaml
- descqa/readiness_test.py
Made some updates to the readiness test (maximum galaxyID check, change on size_bulge_minor check, added optional plot ranges, added Mag* distributions)
https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-04-10_7&catalog=proto-dc2_v4.0_test
> Added galaxyID assert, optional plot ranges and check of Mag*

- descqa/configs/Nz_i_Coil2004_magbin.yaml
Minor change to yaml file to include jackknife errors for N(z) tomographic magnitude bins and to turn the test on by default (preferred by PZ group). See result:
[]https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-05-18_3
> Added jackknife errors and turned on as default test

- descqa/clf_test.py
- descqa/configs/CLF_r.yaml
@yymao I changed the mass and redshift binning scheme in clf_test to make the feature at high mass end more noticeable. 
Here is a run on proto-dc2v4.3 and protodc2v4.5. 
https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-05-31_19&test=CLF_r&catalog=proto-dc2_v4.5
> change clf binning

- descqa/SizeStellarMassLuminosity.py
- descqa/configs/size_Mandelbaum2014_BD.yaml
- descqa/configs/size_vanderWel2014_SM_Lum.yaml
This PR implements the validation criteria on the size-luminosity relations: a chisq/dof<1.2 between sims and validation data set for all tested redshift bins.  [A successful run of this test can be viewed here](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-06-01_17) (all v4 catalogs pass!). If you want to see the failure messages, you can examine [the runs on proto-dc2_v2.0](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-06-01_16).
> Size-luminosity validation criteria

- README.md
- descqa/EllipticityDistribution.py
- descqa/configs/ellipticity_dist.yaml
- descqa/configs/ellipticity_dist_COSMOS.yaml
This code contains the validation criteria for the ellipticity distribution test.  A run of this test on the v4.* catalogs can be found [here](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-05-29_7).  Everything passes except for the late-type galaxies in proto-dc2_v4.5_rescale, where the 10th percentile is a little high (0.41 instead of <=0.4).  I'm not sure that's actually important--I've left if for now so more knowledgeable people can advise me if that's expected or not. It would probably be okay to adjust that criterion if we needed to, however.
The actual validation criteria used here are:
- min(e)>=0
- max(e)<=1
- 10th percentile < 0.4
- 0.3 < 50th percentile < 0.7
- 90th percentile > 0.6
This is tested for all morphologies separately and for the catalog as a whole; the …
> Ellipticity validation

- descqa/configs/readiness_protoDC2.yaml
- descqa/readiness_test.py
The simple `check_column_uniqueness` function just gives wrapper behavior around `np.unique`. The optional `mask` argument means the same function can be used to evaluate the uniqueness of a galaxyID (no mask) or a haloID (masking on central galaxies). 
[edited by @yymao: fixes #135]
> Add uniqueness check in readiness test

- descqa/configs/truth_galaxy_verification_run1.1.yaml
- descqa/truth_galaxy_verification.py
This PR adds a verification test for the galaxies in the truth catalog. You can take a look at [the DESCQA run](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-08-23_8&test=truth_galaxy_verification_run1.1&catalog=dc2_run1.1_extragalactic_truth_match) (As of 5:50p ET, the DESCQA web service is working fine. If you want to check out the plots, you can find them on NERSC at `/global/projecta/projectdirs/lsst/groups/CS/descqa/run/v2/2018-08/2018-08-23_8/truth_galaxy_verification_run1.1/dc2_run1.1_extragalactic_truth_match`.)
Note that, to try out this PR, you need to use this https://github.com/LSSTDESC/gcr-catalogs/pull/174
Here I attached one of the plots that shows the histogram of the difference in the r-band magnitude: 
I am not sure if this is an OK result, I would have …
> add verification test for galaxies in truth catalog

- descqa/ImgPkTest.py
This PR improves the image power spectra test to show per-sensor spectra. 
[A DESCQA run can be found here](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-08-30_46&test=image_power_spec), which shows the test results for e-images of both Run 1.2p and the newly arrived Run 1.2i!
You may still encounter timeout error when visiting the DESCQA web app. You can find the plots on NERSC at `/global/projecta/projectdirs/lsst/groups/CS/descqa/run/v2/2018-08/2018-08-30_46/image_power_spec`. Here I post one of them (raft 24, visit 181898) for both runs (upper two: 1.2p; lower two: 1.2i):
(Note: to run this PR, you'll need the latest gcr-catalogs that contains the updated e-image reader)
> update image psd test to show per-sensor result

- descqarun/master.py
This PR makes sure that, when the execution script creates a new monthly directory for test results, it sets the correct permission (adding `g+ws`) so that other people in the same group can create new subdirectory within.
> set correct permission when execution script creates a directory

- descqa/configs/readiness_instance_agn.yaml
- descqa/configs/readiness_instance_star.yaml
- descqa/readiness_test.py
This PR upgrades the readiness test so that it can display an aggregated summary report when the test is run on multiple catalogs *and* the option `enable_aggregated_summary` is turned on. 
This PR also adds two new test configs that use this new feature to validate the instance catalogs as requested in #152. 
[Here's a test run](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-09-02_6), and you can see aggregated summary report [for AGN mags here](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-09-02_6&test=readiness_instance_agn&right=2018-09/2018-09-02_6/readiness_instance_agn/SUMMARY.html) and [for star mags here](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-09-02_6&test=readiness_instance_star&right=2018-09/2018-09-02_6/readiness_instance_agn/SUMMARY.ht …
> upgrade readiness test to display an aggregated report

- descqaweb/config.py
- descqaweb/main.py
- descqaweb/templates/home.html
As discussed in #160, the current front page is very outdated. Before we come up with a more permanent solution, we should put something more informative on the front page. This PR makes a quick update to the front page.
You can preview this PR here: https://portal.nersc.gov/project/lsst/descqa/v2-new-home/
> update the front page of website

- descqa/configs/shear.yaml
- descqa/shear_test.py
The updates for the test are as follows:
- catch for missing cosmology 
- bug fix for high redshift theory
- magnitude cut to speed up test 
There was a bug stopping the theory correlations being computed above redshift 2, I've also added a magnitude cut for a magnitude quantity and limit defined in the yaml file (note that current default is for umachine set-up) to let the test run in a more reasonable time-frame. 
The portal link should be: https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-08-24_15
> Shear validation test: high-z bug fixes and mag cut implemented

- descqaweb/templates/header.html
This PR updates the HTML header/meta of the DESCQA website to make them follow the new HTML5 standard and also update normalize css version.
> Update HTML header/meta of DESCQA website

- descqa/README.md
- descqa/register.py
- v1/GCRCatalogs/register.py
- v1/descqa/register.py
This issue https://github.com/LSSTDESC/gcr-catalogs/issues/298 about yaml.load being deprecated also affects this repo. This PR switches yaml load to safe_load to fix it.
> switch yaml load to safe_load

- .travis.yml
- setup.py
pip v19 has deprecated `--process-dependency-links` and our CI test will not run. This PR fixes this issue by moving dependency links to regular requirements.
> move dependency link to regular requirement

- descqarun/master.py
- v1/GCRCatalogs/register.py
In `GCRCatalogs` v0.11.0, the attribute `GCRCatalogs.available_catalogs` has been deprecated in favor of the function call `GCRCatalogs.get_available_catalogs()`. This PR makes appropriate updates to the execution script to accommodate this GCRCatalogs API change.
> GCRCatalogs API change: `available_catalogs` deprecated

- descqa/ColorDistribution.py
- descqa/configs/Color_Dist_DEEP2_noagn.yaml
- descqa/configs/Color_Dist_SDSS_noagn.yaml
Color distribution test required minor changes to be able to run on the new AGN catalog. Added a flag to select magnitudes with no agn contributions. Added lsst magnitudes as an option in case SDSS or DES magnitudes are unavailable. If LSST magnitudes used, plot title indicates this. Test results are [here](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2019-08-07_1 ). Test results for default case with AGN magnitudes included are [here](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2019-08-07_2)
> Modifications to run catalogs with or without agn contributions

- descqa/apparent_mag_func_test.py
- descqa/utils.py
Added some cosmetic changes to allow for making better figures. See [here] (https://portal.nersc.gov/project/lsst/descqa/v2/?run=2019-09-19_4) for a test run.
> Cosmetic changes for nicer figures

- descqa/EmlineRatioTest.py
- descqa/configs/EmlineLuminosityRatios.yaml
- setup.py
[Web Interface Link](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2019-11-19_5)
> Added emission line QA test and SDSS comparison data set.

- descqa/EmlineRatioTest.py
- descqa/configs/EmlineLuminosityRatios.yaml
No changes to validation test content, but I have simplified the code so that it no longer converts emission line luminosities to fluxes before performing the test.
> Units fixes for EmissionlineRatioTest

- descqa/EmlineRatioTest.py
Please forgive my stumbling through Git!  This should correct the sins of commit 7a17cbc66b3241675bc14e1641b0a4364ebe6ebc.  It removes unused variables and removes the calculation of emission line fluxes since only the luminosities are needed.
> Corrected bugged commit 7a17cbc66b3241675bc14e1641b0a4364ebe6ebc

- CONTRIBUTING.md
- README.md
- descqa/ColorDistribution.py
- descqa/DensityVersusSkyPosition.py
- descqa/ImgPkTest.py
- descqa/base.py
- descqa/configs/DensityVersusExtinction.yaml
- descqa/configs/image_power_spec.yaml
- descqarun/config.py
- descqaweb/config.py
- run_master.sh
- run_master_v1.sh
- v1/GCRCatalogs/YaleCAMGalaxyCatalog.py
- v1/GCRCatalogs/config.py
- v1/descqa/ColorDistributionTest.py
This PR fixes #198. It moves all the projecta reference to the new cfs space, including web service, test datasets, runs, and catalogs.
> Move to cfs

- .github/workflows/pythonpackage.yml
This PR updates the linter arguments in the CI test to avoid CI test failures due to unnecessary linter complaints.
> Update linter arguments in CI

- descqa/configs/readiness_baseDC2_sm_cut.yaml
- descqa/readiness_test.py
This addition allows a filter to be applied to the catalog data before running the readiness tests. This was useful for testing the new baseDC2_5000 against the old catalog. baseDC2_5000 has a stellar-mass cut applied, which reduces the number of synthetic galaxies. I wanted to apply the same cut to the old baseDC2 catalog to do a comparison. The cosmic variance of the redshift distribution was of particular interest. Here's an [example run for healpixel 9556](https://portal.nersc.gov/cfs/lsst/descqa/v2/?run=2020-05-01_10&test=readiness_baseDC2_sm_cut)
> Add ability to filter catalog before running readiness test

- descqa/shear_test.py
I added a printout of the data points shown in the plots at the request of the WL group who are cross checking with their results and changed the cosmetics to improve the presentation. See https://portal.nersc.gov/cfs/lsst/descqa/v2/?run=2020-12-04_23&test=shear   for an example
> Add printout of data points; improve titles and labels

- descqa/NumberDensityVersusRedshift.py
Here's a minor change I made to allow the code to run on the dr2 catalog.
> Add redshift_truth option to run on dr2

- run_master.sh
DESCQA directly uses the python executable. For it to work with the new desc-python, DESCQA needs to be run within that shifter image. That wasn't expected in the original design.
For now I just switch to `setup_old_python.sh` in `run_master.sh` so that things should continue to work. We still need to find a long-term solution.
> Use `setup_old_python.sh`

- .github/workflows/pythonpackage.yml
Update python test action to use latest actions, improve efficiency, and add Python 3.8 as part of the test.
> Update python action

- .github/workflows/pythonpackage.yml
It took a long time to install all the python dependencies. The full CI run should be skipped if one just changes the README file.
> Run full CI only when needed

- descqa/DeltaSigmaTest.py
- descqa/NumberDensityVersusRedshift.py
- descqa/configs/readiness_roman_rubin.yaml
- run_master.sh
Here are the changes to get the Delta_Sigma and NumberDensityVersusRedshift tests to run with the latest versions of numpy, sklearn etc. These are minor code changes to the actual tests.
There is also an addition required to the run_master script to set the number of OMP_NUM_THREADS.  The issue is that the NumberDensityVersusRedshift test fails with an OPEN_BLAS error that complains about too many threads being used. (This is for a call to the kNN module in sklearn. ) The error did not occur when running on cori.  I have experimented with trying to set the number of OPEN_BLAS_THREADS and OMP_NUM_THREADS by calling  the python function to set these environmentals in the init function of NumberDensityVersusRedshift.py. None of these worked.  The only attempt that worked was to set the …
> Changes for running and testing the roman_rubin catalog
